import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { io } from 'socket.io-client';
const socket = io();

export default function Home() {
  const [message, setMessage] = useState("")
  const [name, setName] = useState("")
  const [allMessages, setAllMessages] = useState([])

  const handleEnter = async (event) => {
    event.preventDefault()
    const res = await fetch('/api/message', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({ name, message }),
    });
    console.log(res)

    setName("")
    setMessage("")
  }

  useEffect(() => {
    socket.off('message');
    socket.on('message', (data) => {
      setAllMessages((oldMessages) => [...oldMessages, data]);
    });
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleEnter}>
          <input type="text" placeholder='Name here' value={name} onChange={(e)=>{setName(e.target.value)}}></input>
          <input type="text" placeholder='Message here' value={message} onChange={(e)=>{setMessage(e.target.value)}}></input>
          <button type="submit">Submit</button>
        </form>
        <div>
          {allMessages && allMessages?.map((o,i)=>{
            return(
              <div key={i}>{o.name}:{o.message}</div>
            )
          })}
        </div>
      </main>
    </>
  )
}
